/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SwapRouteImport } from './routes/swap'
import { Route as LoreRouteImport } from './routes/lore'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPurgeRouteImport } from './routes/api/purge'
import { Route as ProtectedPurgeRouteImport } from './routes/_protected.purge'
import { Route as ProtectedPassportRouteImport } from './routes/_protected.passport'
import { Route as ApiAuthVerifyRouteImport } from './routes/api/auth/verify'
import { Route as ApiAuthNonceRouteImport } from './routes/api/auth/nonce'
import { Route as ApiAuthMeRouteImport } from './routes/api/auth/me'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'

const SwapRoute = SwapRouteImport.update({
  id: '/swap',
  path: '/swap',
  getParentRoute: () => rootRouteImport,
} as any)
const LoreRoute = LoreRouteImport.update({
  id: '/lore',
  path: '/lore',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPurgeRoute = ApiPurgeRouteImport.update({
  id: '/api/purge',
  path: '/api/purge',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedPurgeRoute = ProtectedPurgeRouteImport.update({
  id: '/purge',
  path: '/purge',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedPassportRoute = ProtectedPassportRouteImport.update({
  id: '/passport',
  path: '/passport',
  getParentRoute: () => ProtectedRoute,
} as any)
const ApiAuthVerifyRoute = ApiAuthVerifyRouteImport.update({
  id: '/api/auth/verify',
  path: '/api/auth/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthNonceRoute = ApiAuthNonceRouteImport.update({
  id: '/api/auth/nonce',
  path: '/api/auth/nonce',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthMeRoute = ApiAuthMeRouteImport.update({
  id: '/api/auth/me',
  path: '/api/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/lore': typeof LoreRoute
  '/swap': typeof SwapRoute
  '/passport': typeof ProtectedPassportRoute
  '/purge': typeof ProtectedPurgeRoute
  '/api/purge': typeof ApiPurgeRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/nonce': typeof ApiAuthNonceRoute
  '/api/auth/verify': typeof ApiAuthVerifyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/lore': typeof LoreRoute
  '/swap': typeof SwapRoute
  '/passport': typeof ProtectedPassportRoute
  '/purge': typeof ProtectedPurgeRoute
  '/api/purge': typeof ApiPurgeRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/nonce': typeof ApiAuthNonceRoute
  '/api/auth/verify': typeof ApiAuthVerifyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/docs': typeof DocsRoute
  '/lore': typeof LoreRoute
  '/swap': typeof SwapRoute
  '/_protected/passport': typeof ProtectedPassportRoute
  '/_protected/purge': typeof ProtectedPurgeRoute
  '/api/purge': typeof ApiPurgeRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/nonce': typeof ApiAuthNonceRoute
  '/api/auth/verify': typeof ApiAuthVerifyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/lore'
    | '/swap'
    | '/passport'
    | '/purge'
    | '/api/purge'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/nonce'
    | '/api/auth/verify'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/docs'
    | '/lore'
    | '/swap'
    | '/passport'
    | '/purge'
    | '/api/purge'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/nonce'
    | '/api/auth/verify'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/docs'
    | '/lore'
    | '/swap'
    | '/_protected/passport'
    | '/_protected/purge'
    | '/api/purge'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/nonce'
    | '/api/auth/verify'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  DocsRoute: typeof DocsRoute
  LoreRoute: typeof LoreRoute
  SwapRoute: typeof SwapRoute
  ApiPurgeRoute: typeof ApiPurgeRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthMeRoute: typeof ApiAuthMeRoute
  ApiAuthNonceRoute: typeof ApiAuthNonceRoute
  ApiAuthVerifyRoute: typeof ApiAuthVerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/swap': {
      id: '/swap'
      path: '/swap'
      fullPath: '/swap'
      preLoaderRoute: typeof SwapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lore': {
      id: '/lore'
      path: '/lore'
      fullPath: '/lore'
      preLoaderRoute: typeof LoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/purge': {
      id: '/api/purge'
      path: '/api/purge'
      fullPath: '/api/purge'
      preLoaderRoute: typeof ApiPurgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/purge': {
      id: '/_protected/purge'
      path: '/purge'
      fullPath: '/purge'
      preLoaderRoute: typeof ProtectedPurgeRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/passport': {
      id: '/_protected/passport'
      path: '/passport'
      fullPath: '/passport'
      preLoaderRoute: typeof ProtectedPassportRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/api/auth/verify': {
      id: '/api/auth/verify'
      path: '/api/auth/verify'
      fullPath: '/api/auth/verify'
      preLoaderRoute: typeof ApiAuthVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/nonce': {
      id: '/api/auth/nonce'
      path: '/api/auth/nonce'
      fullPath: '/api/auth/nonce'
      preLoaderRoute: typeof ApiAuthNonceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/me': {
      id: '/api/auth/me'
      path: '/api/auth/me'
      fullPath: '/api/auth/me'
      preLoaderRoute: typeof ApiAuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedPassportRoute: typeof ProtectedPassportRoute
  ProtectedPurgeRoute: typeof ProtectedPurgeRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedPassportRoute: ProtectedPassportRoute,
  ProtectedPurgeRoute: ProtectedPurgeRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  DocsRoute: DocsRoute,
  LoreRoute: LoreRoute,
  SwapRoute: SwapRoute,
  ApiPurgeRoute: ApiPurgeRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthMeRoute: ApiAuthMeRoute,
  ApiAuthNonceRoute: ApiAuthNonceRoute,
  ApiAuthVerifyRoute: ApiAuthVerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
